name: Daily Commit

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make changes
        run: |
          echo "Last run: $(date -u)" > changelog.txt

      - name: Commit changes 
        run: |
          git config --global user.name "karthikiitm"
          git config --global user.email "23f1001174@ds.study.iitm.ac.in"
          git add changelog.txt
          git commit -m "Daily update: $(date -u)" || echo "No changes to commit."  # Avoid failure if no changes
          git push
